---
- name: deploy postgres on vagrant
  hosts: db
  vars_files:
    - secrets.yml
  roles:
    - role: database
      database_name: "{{ mezzanine_proj_name }}"
      database_user: "{{ mezzanine_proj_name }}"
      postgres_data: /var/lib/pgsql/data

- name: deploy mezzanine on vagrant
  hosts: web
  vars_files:
    - secrets.yml
  roles:
    - role: mezzanine
      database_host: "{{ hostvars.db.ansible_eth1.ipv4.address }}"
      live_hostname: "{{ ansible_eth1.ipv4.address }}.xip.io"
      domains: 
        - "{{ ansible_eth1.ipv4.address }}.xip.io"
        - "www.{{ ansible_eth1.ipv4.address }}.xip.io"