---
# handlers file for mezzanine
- name: start and enabled gunicorn service
  systemd: state=restarted daemon_reload=yes enabled=yes name=gunicorn
  become: True

- name: restart nginx
  systemd: name=nginx state=restarted enabled=yes
  become: True
