---
# tasks file for mezzanine
- name: add nginx repo
  yum_repository:
    name: nginx
    description: nginx repo
    file: nginx
    baseurl: http://nginx.org/packages/centos/7/$basearch/
    gpgcheck: no
    enabled: yes
  become: True
- name: install epel
  yum: name=epel-release state=latest update_cache=yes
  become: True

- name: install yum packages
  yum: name={{ item }} state=latest update_cache=yes 
  become: True
  with_items:
    - git
    - vim
    - libjpeg-turbo-devel
    - memcached
    - nginx
    - python-devel
    - python2-pip
    - python-setuptools
    - python-virtualenv
    - supervisor
    - gcc
    - net-tools
    - libsemanage-python
    - python-psycopg2

- include: django.yml

- include: nginx.yml