#!/usr/bin/env ansible-playbook
---
- name: Configure webserver with nginx
  hosts: web
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/conf.d/default.conf
    server_name: localhost
  tasks:
    - name: add nginx repo
      yum_repository:
        name: nginx
        description: nginx repo
        file: nginx
        baseurl: http://nginx.org/packages/centos/7/$basearch/
        gpgcheck: no
        enabled: yes
    - name: install epel
      yum: name=epel-release state=latest update_cache=yes

    - name: install nginx
      yum: name=nginx state=latest update_cache=yes

    - name: create directory for ssl certificate
      file: path=/etc/nginx/ssl state=directory

    - name: Copy TLS key
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: restart nginx

    - name: copy TLS certificate
      copy: src=files/nginx.crt dest={{ cert_file }}
      notify: restart nginx

    - name: copy nginx config files
      template: src=templates/nginx.conf.j2 dest={{ conf_file }}
      notify: restart nginx

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
  
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted         
